### ISSUE TITLE
AssertionError in mxDateTime/test.py

### ISSUE THREAD

**Issue by rfleschenberg** [egenix/egenix-mx-base-python-2x3#4]
Running Python datetime module integration tests.

```
Running slot operation tests.
Traceback (most recent call last):
  File "mx/DateTime/mxDateTime/test.py", line 721, in <module>
    from mx.DateTime.mxDateTime import testslotops
  File "/home/rene/egenix-mx-base-python-2x3/egenix-mx-base-3.2.9/.tox/py27/local/lib/python2.7/site-packages/mx/DateTime/mxDateTime/testslotops.py", line 516, in <module>
    run_tests()
  File "/home/rene/egenix-mx-base-python-2x3/egenix-mx-base-3.2.9/.tox/py27/local/lib/python2.7/site-packages/mx/DateTime/mxDateTime/testslotops.py", line 57, in run_tests
    assert t1 < td1
AssertionError
```

**Comment by rfleschenberg** [comment]
This comparison is indeterministic in Python 2 (compares by id). We should just remove the asserts and close the issue.
